title: Warung Kopinank
email: lovely.ariesan@gmail.com
description: Warung Kopi Terbaik di Gegesik
baseurl: "/kopinank"
url: ""
permalink: /:categories/:title:output_ext

instagram_username:

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag