title: Warung Kopinank
email: lovely.ariesan@gmail.com
description: Warung Kopi Terbaik di Gegesik
baseurl: ""
url: "https://ariesan.github.io/warung-kopinank/"
permalink: /:categories/:title:output_ext

instagram_username:

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag